// <auto-generated />
using System;
using AngularNetCoreSample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngularNetCoreSample.Migrations
{
    [DbContext(typeof(ClientDBContext))]
    [Migration("20181113195418_init555")]
    partial class init555
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AngularNetCoreSample.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<int>("CommandeCount");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AngularNetCoreSample.Data.Entities.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId");

                    b.Property<decimal>("Price");

                    b.Property<int>("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("AngularNetCoreSample.Data.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommandeId");

                    b.Property<string>("productCategory");

                    b.Property<string>("productDescription");

                    b.Property<string>("productName");

                    b.Property<int>("productPrice");

                    b.Property<int>("productWeight");

                    b.HasKey("ID");

                    b.HasIndex("CommandeId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("AngularNetCoreSample.Data.Entities.Commande", b =>
                {
                    b.HasOne("AngularNetCoreSample.Data.Entities.Client")
                        .WithMany("Commandes")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("AngularNetCoreSample.Data.Entities.Product", b =>
                {
                    b.HasOne("AngularNetCoreSample.Data.Entities.Commande")
                        .WithMany("Products")
                        .HasForeignKey("CommandeId");
                });
#pragma warning restore 612, 618
        }
    }
}
